---
- hosts: localhost
  gather_facts: true
  connection: local


  vars:
    inventory: "{{ lookup('env', 'INVENTORY_JSON') | from_json }}"
    host:   "{{ inventory[0] }}"
    hostname: "{{ host.hostname | default('') }}"
    dns_name:      "{{ host.dns_name      | default('') }}"
    service_ip:            "{{ host.service_ip            | default('') }}"
    bmc_ip:   "{{ host.bmc_ip   | default('') }}"
    gateway:       "{{ host.gateway       | default('') }}"
    dns_server:    "{{ host.dns_server    | default('') }}"
    ntp_server:    "{{ host.ntp_server    | default('') }}"
    vlan_id:       "{{ host.vlan_id       | default('') }}"
    esxi_version:  "{{ host.esxi_version  | default('') }}"
    username:      "{{ host.username      | default('') }}"
    vendor:        "{{ host.vendor        | default('') }}"

  tasks:
    - name: Create Custom EXSi ISO File
      include_role:
        name: installESXi
        tasks_from: create_ESXi_custom_ISO.yml
