- name: Dell Server reboot 
  uri:
    url: "https://{{ bmc_ip }}/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset"
    method: POST
    user: "{{ username }}"
    password: "{{ password }}"
    force_basic_auth: true
    validate_certs: false
    body_format: json
    body:
      ResetType: "ForceRestart"
    status_code: [200, 202, 204]
  register: result_dell_server_reboot


- name: Debug Dell Server Reboot
  ansible.builtin.debug:
    msg: "{{ result_dell_server_reboot }}"
