- name: Pre-Check hosts Directory
  stat:
    path: "/ansible-semaphore/windows/hosts/{{ hostname }}"
  register: check_dir

- name: Fail if exists
  fail:
    msg: "Directory already exists"
  when: check_dir.stat.exists