---
- name: Windows baseline 구성 적용 (w32time + legalnotice)
  hosts: all
  connection: winrm
  gather_facts: true

  vars_files:
    - "{{ lookup('env', 'REPO_ROOT') }}/vault/windows.yml"

  vars:
    ansible_winrm_transport:              ntlm
    ansible_winrm_scheme:                 http
    ansible_port:                         5985
    ansible_winrm_server_cert_validation: ignore

  roles:
    - w32time
    - legalnotice
