  - name: Copy base image to host directory
    copy:
      src: "/ansible-semaphore/base-img/ISO/REDHAT/{{ rhel_version }}/"
      dest: "/ansible-semaphore/redhat/hosts/{{ hostname }}/base-img/"
      remote_src: yes