- name: Set common variables
  set_fact:
    version: "{{ esxi_version | default(rhel_version) | default(win_version) }}"
    os_type: "{{ 'esxi' if esxi_version is defined else ('redhat' if rhel_version is defined else 'windows') }}"

- name: HP virtual media unmount before mount
  uri:
    url: "https://{{ bmc_ip }}/redfish/v1/Managers/1/VirtualMedia/2/Actions/VirtualMedia.EjectMedia"
    method: POST
    user: "{{ username }}"
    password: "{{ password }}"
    body_format: json
    status_code: [200, 202, 204, 400]
    force_basic_auth: yes
    validate_certs: false
  register: eject1_result
  failed_when: >
    eject1_result.status == 400 and
    (
      eject1_result.json is not defined or
      eject1_result.json.error is not defined or
      eject1_result.json.error['@Message.ExtendedInfo'] is not defined or
      eject1_result.json.error['@Message.ExtendedInfo'] | length == 0 or
      'NoVirtualMedia' not in eject1_result.json.error['@Message.ExtendedInfo'][0].MessageId
    )
  changed_when: eject1_result.status in [200, 202, 204]

- name: CD/DVD Network File Eject result
  ansible.builtin.debug:
    msg: >-
      {{
        "CD/DVD media ejected successfully"
        if eject1_result.json.error['@Message.ExtendedInfo'][0].MessageId
           == 'Base.1.10.Success'
        else
        "No virtual media was attached"
      }}

- name: Mount RHEL8.10 Media
  uri:
    url: "https://{{ bmc_ip }}/redfish/v1/Managers/1/VirtualMedia/2/Actions/VirtualMedia.InsertMedia"
    method: POST
    user: "{{ username }}"
    password: "{{ password }}"
    body_format: json
    body:
      Image: "http://10.50.21.40/{{ os_type }}/hosts/{{ hostname }}/{{ version }}-custom-{{ hostname }}.iso"
      Inserted: true
    status_code: [200, 202, 204, 400]
    force_basic_auth: yes
    validate_certs: false
  register: insert_result
