---
- hosts: localhost
  gather_facts: true
  connection: local

  vars_files:
    - ../../group_vars/all.yml

  vars:
    inventory: "{{ lookup('env', 'INVENTORY_JSON') | from_json }}"
    host:   "{{ inventory[0] }}"
    hostname: "{{ host.hostname | default('') }}"
    dns_name:     "{{ host.dns_name     | default('') }}"
    service_ip:           "{{ host.service_ip           | default('') }}"
    bmc_ip:  "{{ host.bmc_ip  | default('') }}"
    gateway:      "{{ host.gateway      | default('') }}"
    dns_server:   "{{ host.dns_server   | default('') }}"
    ntp_server:   "{{ host.ntp_server   | default('') }}"
    vlan_id:      "{{ host.vlan_id      | default('') }}"
    win_version:  "{{ host.win_version  | default('') }}"
    username:     "{{ host.username     | default('') }}"
    vendor:       "{{ host.vendor       | default('') }}"
    vendor_name:
      lenovo:
        role: bmc
        task: lenovo/set_onetime_boot.yml
      
      hp:
        role: bmc
        task: hp/set_onetime_boot.yml

  tasks:
    - name: "Set one-time boot process"
      include_role:
        name: "{{ vendor_name[vendor].role }}"
        tasks_from: "{{ vendor_name[vendor].task }}"
