---
- hosts: localhost
  gather_facts: true
  connection: local

  vars:
    inventory: "{{ lookup('env', 'INVENTORY_JSON') | from_json }}"
    host:   "{{ inventory[0] }}"
    bmc_ip:          "{{ host.bmc_ip          | default('') }}"
    username:             "{{ host.username             | default('') }}"
    vendor:               "{{ host.vendor               | default('') }}"
    workload_profile:     "{{ host.workload_profile     | default('') }}"
    acpi_slit:            "{{ host.acpi_slit            | default('') }}"
    thermal_shutdown:     "{{ host.thermal_shutdown     | default('') }}"
    fan_fail_policy:      "{{ host.fan_fail_policy      | default('') }}"
    daylight_saving_time: "{{ host.daylight_saving_time | default('') }}"
    vendor_name:
      hp:
        role: bios
        task: hp/check_parameters.yml
      
  tasks:
    - name: Validate vendor variable
      ansible.builtin.assert:
        that:
          - vendor is defined
          - vendor | length > 0
          - vendor in vendor_name.keys()
        fail_msg: "Invalid vendor value: {{ vendor | default('undefined') }}. Support vendors: {{ vendor_name.keys() | join(', ') }}"

    - name: "Check parameters variable"
      include_role:
        name: "{{ vendor_name[vendor].role }}"
        tasks_from: "{{ vendor_name[vendor].task }}"
