---
- name: ESXi uptime 조회
  hosts: all
  gather_facts: false
  connection: ssh

  vars_files:
    - "{{ lookup('env', 'REPO_ROOT') }}/vault/esxi.yml"

  tasks:
    - ansible.builtin.command: uptime
      register: up
      changed_when: false

    - ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ up.stdout }}"
