---
- hosts: localhost
  gather_facts: true
  connection: local

  vars:
    inventory: "{{ lookup('env', 'INVENTORY_JSON') | from_json }}"
    host:   "{{ inventory[0] }}"
    bmc_ip:        "{{ host.bmc_ip        | default('') }}"
    username:           "{{ host.username           | default('') }}"
    vendor:             "{{ host.vendor             | default('') }}"
    OperatingMode_STP1: "{{ host.OperatingMode_STP1 | default('') }}"
    OperatingMode_STP2: "{{ host.OperatingMode_STP2 | default('') }}"
    MONITORMWAIT:       "{{ host.MONITORMWAIT       | default('') }}"
    CStates:            "{{ host.CStates            | default('') }}"
    Intel_VT:           "{{ host.Intel_VT           | default('') }}"
    vendor_name:
      lenovo:
        role: bios
        task: lenovo/check_parameters.yml
      
  tasks:
    - name: Validate vendor variable
      ansible.builtin.assert:
        that:
          - vendor is defined
          - vendor | length > 0
          - vendor in vendor_name.keys()
        fail_msg: "Invalid vendor value: {{ vendor | default('undefined') }}. Support vendors: {{ vendor_name.keys() | join(', ') }}"

    - name: "Check parameters variable"
      include_role:
        name: "{{ vendor_name[vendor].role }}"
        tasks_from: "{{ vendor_name[vendor].task }}"
